// Firebase configuration - Generated by FlutterFire CLI
// Update this file with your Firebase project configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'YOUR_ANDROID_API_KEY',
          appId: 'YOUR_ANDROID_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'fmg-app',
          databaseUrl: 'https://fmg-app.firebaseio.com',
          storageBucket: 'fmg-app.appspot.com',
        );
      case TargetPlatform.ios:
        return const FirebaseOptions(
          apiKey: 'YOUR_IOS_API_KEY',
          appId: 'YOUR_IOS_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'fmg-app',
          databaseUrl: 'https://fmg-app.firebaseio.com',
          storageBucket: 'fmg-app.appspot.com',
          iosBundleId: 'com.fmg.companion',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'YOUR_MACOS_API_KEY',
          appId: 'YOUR_MACOS_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'fmg-app',
          databaseUrl: 'https://fmg-app.firebaseio.com',
          storageBucket: 'fmg-app.appspot.com',
          iosBundleId: 'com.fmg.companion',
        );
      case TargetPlatform.web:
        return const FirebaseOptions(
          apiKey: 'YOUR_WEB_API_KEY',
          appId: 'YOUR_WEB_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'fmg-app',
          databaseUrl: 'https://fmg-app.firebaseio.com',
          storageBucket: 'fmg-app.appspot.com',
          authDomain: 'fmg-app.firebaseapp.com',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}