// Firebase configuration - Generated by FlutterFire CLI
// Run: cd mobile && flutterfire configure --project=fmg-companion-app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for the FMG Companion App (fmg-companion-app)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: $defaultTargetPlatform',
        );
    }
  }

  // ─── ANDROID ────────────────────────────────────────────────────────────────
  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyCMfvStTnqQ865jSBlYZaCk6VPih2nN_Lg',
    appId: '1:286291793703:android:3d17e50d9269106a6a3b02',
    messagingSenderId: '286291793703',
    projectId: 'fmg-companion-app',
    databaseUrl: 'https://fmg-companion-app.firebaseio.com',
    storageBucket: 'fmg-companion-app.firebasestorage.app',
  );

  // ─── IOS ──────────────────────────────────────────────────────────────────
  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyCPU9pTu1y9rgBw4PBSRowun_VvZedLIOs',
    appId: '1:286291793703:ios:f770fb22634c0d466a3b02',
    messagingSenderId: '286291793703',
    projectId: 'fmg-companion-app',
    databaseUrl: 'https://fmg-companion-app.firebaseio.com',
    storageBucket: 'fmg-companion-app.firebasestorage.app',
    iosBundleId: 'com.fmg.companion',
  );

  // ─── MACOS ───────────────────────────────────────────────────────────────
  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: 'AIzaSyCPU9pTu1y9rgBw4PBSRowun_VvZedLIOs',
    appId: '1:286291793703:ios:f770fb22634c0d466a3b02',
    messagingSenderId: '286291793703',
    projectId: 'fmg-companion-app',
    databaseUrl: 'https://fmg-companion-app.firebaseio.com',
    storageBucket: 'fmg-companion-app.firebasestorage.app',
    iosBundleId: 'com.fmg.companion',
  );

  // ─── WEB ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'AIzaSyCgZXr-OWLTRpONU1Ky0QVikh3LlNmM8Eo',
    appId: '1:286291793703:web:95fb7ddec5da70cb6a3b02',
    messagingSenderId: '286291793703',
    projectId: 'fmg-companion-app',
    databaseUrl: 'https://fmg-companion-app.firebaseio.com',
    storageBucket: 'fmg-companion-app.firebasestorage.app',
    authDomain: 'fmg-companion-app.firebaseapp.com',
  );
}