// Firebase configuration - Generated by FlutterFire CLI
// Run: cd mobile && flutterfire configure
// This will generate the real config values for your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// DefaultFirebaseOptions holds the platform-specific Firebase configuration.
///
/// To generate real values:
///
///   1. Install the Firebase CLI: npm install -g firebase-tools
///   2. Login: firebase login
///   3. Run: flutterfire configure --project=YOUR_PROJECT_ID
///   4. This file will be auto-generated with your actual keys
///
/// Until configured, the app will compile but fail to connect to Firebase.
///
/// Platform support:
///   - Android: apiKey, appId, messagingSenderId, projectId, storageBucket
///   - iOS:     apiKey, appId, messagingSenderId, projectId, iosBundleId, storageBucket
///   - Web:     apiKey, appId, messagingSenderId, projectId, authDomain, storageBucket
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: $defaultTargetPlatform',
        );
    }
  }

  // ─── ANDROID ────────────────────────────────────────────────────────────────
  // Replace these values by running: flutterfire configure
  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',          // From Firebase Console → Project Settings → Your apps → Android
    appId: 'YOUR_ANDROID_APP_ID',            // Same location, e.g. "1:123456789:android:abc123"
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Project Settings → Cloud Messaging → Sender ID
    projectId: 'fmg-app',                    // Your Firebase project ID
    databaseUrl: 'https://fmg-app.firebaseio.com',
    storageBucket: 'fmg-app.appspot.com',
  );

  // ─── IOS ──────────────────────────────────────────────────────────────────
  // Replace these values by running: flutterfire configure
  // Also ensure GoogleService-Info.plist is in ios/Runner/
  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',              // From Firebase Console → Project Settings → Your apps → iOS
    appId: 'YOUR_IOS_APP_ID',                // e.g. "1:123456789:ios:abc123"
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fmg-app',
    databaseUrl: 'https://fmg-app.firebaseio.com',
    storageBucket: 'fmg-app.appspot.com',
    iosBundleId: 'com.fmg.companion',        // Must match the bundle ID in your Apple Developer account
  );

  // ─── MACOS ────────────────────────────────────────────────────────────────
  // Replace these values by running: flutterfire configure
  // Also ensure GoogleService-Info.plist is in macos/Runner/
  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fmg-app',
    databaseUrl: 'https://fmg-app.firebaseio.com',
    storageBucket: 'fmg-app.appspot.com',
    iosBundleId: 'com.fmg.companion',
  );

  // ─── WEB ─────────────────────────────────────────────────────────────────
  // Replace these values by running: flutterfire configure
  // Also ensure firebase.js is loaded in web/index.html
  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',              // From Firebase Console → Project Settings → Your apps → Web
    appId: 'YOUR_WEB_APP_ID',                // e.g. "1:123456789:web:abc123"
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fmg-app',
    databaseUrl: 'https://fmg-app.firebaseio.com',
    storageBucket: 'fmg-app.appspot.com',
    authDomain: 'fmg-app.firebaseapp.com',    // Must match the domain configured in Firebase Auth
  );
}

/// Checklist before running on a real device:
///   [ ] Run `flutterfire configure` in the mobile/ directory
///   [ ] Download GoogleService-Info.plist for iOS/macOS → place in ios/Runner/ and macos/Runner/
///   [ ] Download google-services.json for Android → place in android/app/
///   [ ] Enable Authentication: Firebase Console → Authentication → Sign-in method → Email Link
///   [ ] Enable Firestore: Firebase Console → Firestore Database → Create database (start in test mode)
///   [ ] Deploy Cloud Functions: cd functions && npm install && firebase deploy --only functions
